### PR TITLE
Adds Gleam text + lucy in a single svg

### PR DESCRIPTION
**Pull request by NicklasXYZ**
Not sure it's something that is wanted for this repo.
I've used these combined svgs for a couple of projects.
It might be others could use them in some way as well :)

### CODE REVIEW

**Comment by tynanbe** [comment]
Maybe these should go in a `logo` directory instead of `combined`?

**Comment by lpil** [comment]
Good idea, let's do that

**Comment by NicklasXYZ** [comment]
Alright. Changed the dir name :)

**Review by lpil — APPROVED** [review]
Thank you

**Pull request merged**
