### PR TITLE
Clean up Lucy lib svg

### PR DESCRIPTION
**Pull request by tynanbe**

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
What does this change?

**Comment by tynanbe** [comment]
Removes some unneeded (and unwanted) styles and classes.
Sorts the limbs in clockwise order, starting from Lucy's head.
Also arranges the paths in the source code to match the order in which they appear visually, from the top down.

**Comment by lpil** [comment]
Fab! Though I think she might be the wrong colour now? Looks like a hard black?

**Comment by tynanbe** [comment]
There's no color/style applied now (black is a default), the markup just contains the raw paths.

By omitting styling for this particular file, users can then easily choose their own for the works they create (some Lucys might wear `#ffaff3`, for example).

You can see with the new Lucys I made that perhaps the cleanest way to style a work is by grouping the finalized limbs and setting a fill color on that group.

I didn't group the limbs in this file because it makes it more difficult to select them individually, which is the intended use. If they were grouped, however, it might be good to set that group's fill color to the standard Gleam charcoal (`#282828`).

**Comment by lpil** [comment]
I think it would be nice to set the colour, otherwise I think it would be easy for people to forget and use the black colour instead.

**Comment by tynanbe** [comment]
@lpil, I set the fill for each individual limb to Gleam charcoal.

**Review by lpil — APPROVED** [review]
💜

**Pull request merged**
